name: Flaky Test Detector Alternative 3

on:
  workflow_dispatch:
  pull_request:

jobs:
  run-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Install go-junit-report
        run: go install github.com/jstemmer/go-junit-report@latest
        
      - name: First test run
        id: first_run
        continue-on-error: true
        run: |
          mkdir -p test-results
          # Run tests and capture output
          go test -v -json ./test/... > test-results/results-1.json
      - name: Check first run result
        if: steps.first_run.outcome == 'success'
        run: echo "First run passed, no flakiness detected."

      - name: Second test run (only if first run failed)
        id: second_run
        if: steps.first_run.outcome != 'success'
        continue-on-error: true
        run: |
          go test -v -json ./test/... > test-results/results-2.json

      - name: Fail if second run fails
        if: steps.first_run.outcome != 'success' && steps.second_run.outcome == 'failure'
        run: |
          echo "Test failed again. Not flaky — real failure."
          exit 1

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
